In [123]:
import pandas as pd
path = "/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC/data_raw/MELD/"

train_df = pd.read_csv(path + "train_sent_emo.csv")
test_df = pd.read_csv(path + "test_sent_emo.csv")
val_df = pd.read_csv(path + "dev_sent_emo.csv")

In [124]:
train_df.head()

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0,8,21,"00:16:16,059","00:16:21,731"
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1,8,21,"00:16:21,940","00:16:23,442"
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2,8,21,"00:16:23,442","00:16:26,389"
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3,8,21,"00:16:26,820","00:16:29,572"
4,5,My duties? All right.,Chandler,surprise,positive,0,4,8,21,"00:16:34,452","00:16:40,917"

In [125]:
train_df['Emotion'].unique()

<ArrowStringArray>
['neutral', 'surprise', 'fear', 'sadness', 'joy', 'disgust', 'anger']
Length: 7, dtype: str

In [126]:
test_df.head()

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,Why do all youre coffee mugs have numbers on ...,Mark,surprise,positive,0,0,3,19,"00:14:38,127","00:14:40,378"
1,2,Oh. Thats so Monica can keep track. That way ...,Rachel,anger,negative,0,1,3,19,"00:14:40,629","00:14:47,385"
2,3,Y'know what?,Rachel,neutral,neutral,0,2,3,19,"00:14:56,353","00:14:57,520"
3,19,"Come on, Lydia, you can do it.",Joey,neutral,neutral,1,0,1,23,"0:10:44,769","0:10:46,146"
4,20,Push!,Joey,joy,positive,1,1,1,23,"0:10:46,146","0:10:46,833"

In [127]:
val_df.head()

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,"Oh my God, hes lost it. Hes totally lost it.",Phoebe,sadness,negative,0,0,4,7,"00:20:57,256","00:21:00,049"
1,2,What?,Monica,surprise,negative,0,1,4,7,"00:21:01,927","00:21:03,261"
2,3,"Or! Or, we could go to the bank, close our acc...",Ross,neutral,neutral,1,0,4,4,"00:12:24,660","00:12:30,915"
3,4,Youre a genius!,Chandler,joy,positive,1,1,4,4,"00:12:32,334","00:12:33,960"
4,5,"Aww, man, now we wont be bank buddies!",Joey,sadness,negative,1,2,4,4,"00:12:34,211","00:12:37,505"

In [128]:
import sys
import os
import yaml
import pandas as pd
import pprint

# パスの設定
project_root = "/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC"
if project_root not in sys.path:
    sys.path.append(project_root)

from utils.data_utils import get_iemocap_utterances

# 1. Configの読み込み
config_path = os.path.join(project_root, "configs", "config.yaml")
with open(config_path, "r") as f:
    config = yaml.safe_load(f)

iemocap_root = os.path.join(project_root, config["paths"]["iemocap_root"])

raw_labels = ["neu", "ang", "sad", "hap", "exc", "fru", "sur", "fea", "dis", "oth", "xxx"]
identity_map = {label: label for label in raw_labels}

# excludeを空にして、すべてのラベルを救出する
exclude_none = []

# 2. データの取得（自作の文字マップを渡す）
utterances = get_iemocap_utterances(iemocap_root, identity_map, exclude_none)

# 3. DataFrameに変換して確認
iemocap_df = pd.DataFrame(utterances)
iemocap_df.head()

,utt_id,session,dialog,speaker,emotion,emotion_name,wav_path,text
0,Ses01F_script02_2_F000,Session1,Ses01_script02_2,Ses01F,neu,neu,/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC...,
1,Ses01F_script02_2_F001,Session1,Ses01_script02_2,Ses01F,neu,neu,/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC...,
2,Ses01F_script02_2_F002,Session1,Ses01_script02_2,Ses01F,xxx,xxx,/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC...,
3,Ses01F_script02_2_F003,Session1,Ses01_script02_2,Ses01F,xxx,xxx,/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC...,
4,Ses01F_script02_2_F004,Session1,Ses01_script02_2,Ses01F,xxx,xxx,/home/rtakahashi-tmp-pufferfish/rtakahashi/EPC...,

In [129]:
iemocap_df['emotion'].unique()

<ArrowStringArray>
['neu', 'xxx', 'ang', 'fru', 'sad', 'hap', 'sur', 'exc', 'oth', 'fea', 'dis']
Length: 11, dtype: str